export const CHILDREN = [
  {
    name:"Lívia Souza", first:"Lívia", initials:"LS", turma:"8º Ano A", mat:"2026004521",
    turno:"Turno manhã", curso:"Ensino Fundamental II", situacao:"Cursando",
    home:{media:"8,7", freq:"96%", comunicados:3, autorizacoes:2},
    calendarioSubtitle:"Datas, feriados, avaliações e eventos do ano letivo. Itens destacados dizem respeito à turma de Lívia (8º Ano A).",
    horarioNota:"Sala-base: Sala 12, exceto Educação Física (Quadra poliesportiva) e Arte (Sala de Artes).",
    horario:[
      {time:"07:00–07:50",cells:[{s:"Matemática",p:"Prof. João Lima"},{s:"Português",p:"Profa. Ana Cristina"},{s:"História",p:"Prof. Carlos Eduardo"},{s:"Geografia",p:"Profa. Renata Alves"},{s:"Inglês",p:"Prof. Lucas Ferreira"}]},
      {time:"07:50–08:40",cells:[{s:"Português",p:"Profa. Ana Cristina"},{s:"Matemática",p:"Prof. João Lima"},{s:"Inglês",p:"Prof. Lucas Ferreira"},{s:"Ciências",p:"Profa. Mariana Duarte"},{s:"História",p:"Prof. Carlos Eduardo"}]},
      {time:"08:40–09:30",cells:[{s:"História",p:"Prof. Carlos Eduardo"},{s:"Geografia",p:"Profa. Renata Alves"},{s:"Matemática",p:"Prof. João Lima"},{s:"Português",p:"Profa. Ana Cristina"},{s:"Educação Física",p:"Prof. Rafael Costa",room:"Quadra poliesportiva"}]},
      {breakRow:"INTERVALO · 09:30 – 09:50"},
      {time:"09:50–10:40",cells:[{s:"Ciências",p:"Profa. Mariana Duarte"},{s:"Arte",p:"Profa. Beatriz Nunes",room:"Sala de Artes"},{s:"Educação Física",p:"Prof. Rafael Costa",room:"Quadra poliesportiva"},{s:"Matemática",p:"Prof. João Lima"},{s:"Geografia",p:"Profa. Renata Alves"}]},
      {time:"10:40–11:30",cells:[{s:"Inglês",p:"Prof. Lucas Ferreira"},{s:"Ciências",p:"Profa. Mariana Duarte"},{s:"Português",p:"Profa. Ana Cristina"},{s:"Arte",p:"Profa. Beatriz Nunes",room:"Sala de Artes"},{s:"Matemática",p:"Prof. João Lima"}]},
    ],
    boletim:{
      badge:"Aprovada · Média 8,7",
      rows:[
        {d:"Matemática",n:["8,5","9,0","8,0","9,2"],avg:"8,7"},
        {d:"Português",n:["9,0","8,5","9,2","9,0"],avg:"8,9"},
        {d:"História",n:["8,0","8,5","9,0","8,8"],avg:"8,6"},
        {d:"Geografia",n:["8,5","5,8","8,7","9,0"],avg:"8,0",low:2},
        {d:"Ciências",n:["9,0","8,8","9,2","9,5"],avg:"9,1"},
        {d:"Inglês",n:["8,0","8,5","9,0","9,0"],avg:"8,6"},
        {d:"Arte",n:["9,5","9,0","9,5","9,8"],avg:"9,5"},
        {d:"Educação Física",n:["9,0","9,5","9,0","9,5"],avg:"9,3"},
      ],
    },
    frequencia:{
      badge:"Frequência regular",
      summary:[
        {v:"490",l:"Total de aulas"},{v:"471",l:"Presenças",cls:"hi"},{v:"19",l:"Faltas",cls:"warn"},
        {v:"96%",l:"Frequência geral",cls:"hi"},{v:"15",l:"Faltas justificadas"},{v:"4",l:"Faltas não justificadas",cls:"warn"},
      ],
      disciplinas:[
        {d:"Matemática",aulas:80,pres:76,falt:4,freq:"95%"},{d:"Português",aulas:80,pres:78,falt:2,freq:"97,5%"},
        {d:"História",aulas:60,pres:57,falt:3,freq:"95%"},{d:"Geografia",aulas:60,pres:58,falt:2,freq:"96,7%"},
        {d:"Ciências",aulas:70,pres:66,falt:4,freq:"94,3%"},{d:"Inglês",aulas:60,pres:59,falt:1,freq:"98,3%"},
        {d:"Arte",aulas:40,pres:39,falt:1,freq:"97,5%"},{d:"Educação Física",aulas:40,pres:38,falt:2,freq:"95%"},
      ],
      justificativas:[
        {data:"10/03/2026",d:"Matemática",motivo:"Consulta médica",ok:true},
        {data:"22/04/2026",d:"Português",motivo:"Atestado médico",ok:true},
        {data:"18/05/2026",d:"Geografia",motivo:"Viagem em família (com atestado)",ok:true},
        {data:"02/06/2026",d:"Ciências",motivo:"Consulta odontológica",ok:true},
        {data:"15/07/2026",d:"Inglês",motivo:"Não informado",ok:false},
      ],
    },
    autorizacoes:[
      {titulo:"Autorização para passeio escolar",status:"pendente",tipo:"excursao",desc:"Passeio ao Museu de Ciências. Saída às 8h e retorno às 12h, com acompanhamento de dois professores.",meta:["📅 Enviada em 15/04/2026","⏳ Prazo de resposta: 22/04/2026"],pend:true,
        detalhes:{
          local:"Museu de Ciências e Tecnologia — Centro",
          data:"29/04/2026 (quarta-feira)",
          saida:"08h00 — Portão principal da escola",
          retorno:"12h00 (previsto) — mesmo local de saída",
          transporte:"Ônibus fretado pela escola (ida e volta)",
          responsaveis:"Prof. Carlos Eduardo e Profa. Renata Alves",
          custo:"Gratuito — sem custo para as famílias",
          levar:"Uniforme escolar, garrafa de água, lanche leve e boné",
          contatoEmergencia:"Secretaria da escola: (85) 3421-0090",
          observacoes:"Alunos devem retornar para a escola até o horário previsto. Em caso de atraso, os responsáveis serão avisados por telefone.",
        }},
      {titulo:"Autorização para uso de imagem",status:"autorizada",tipo:"imagem",desc:"Uso de fotos e vídeos da aluna em eventos escolares para divulgação em redes sociais oficiais da escola.",meta:["📅 Enviada em 05/02/2026","✔️ Respondida em 06/02/2026"],pend:false,
        detalhes:{
          finalidade:"Divulgação institucional em redes sociais, mural e site da escola",
          validade:"Ano letivo de 2026, podendo ser renovada anualmente",
          canais:"Instagram, Facebook e site oficiais da escola",
          revogacao:"A autorização pode ser revogada a qualquer momento mediante solicitação por escrito à secretaria",
        }},
      {titulo:"Autorização para atividade externa",status:"pendente",tipo:"excursao",desc:"Visita técnica à Feira de Ciências Municipal, com transporte fornecido pela escola.",meta:["📅 Enviada em 20/05/2026","⏳ Prazo de resposta: 27/05/2026"],pend:true,
        detalhes:{
          local:"Centro de Eventos Municipal — Feira de Ciências",
          data:"03/06/2026 (quarta-feira)",
          saida:"07h30 — Portão principal da escola",
          retorno:"11h30 (previsto) — mesmo local de saída",
          transporte:"Ônibus fretado pela escola (ida e volta)",
          responsaveis:"Profa. Mariana Duarte e Prof. João Lima",
          custo:"Gratuito — sem custo para as famílias",
          levar:"Uniforme escolar, garrafa de água e caderno de anotações",
          contatoEmergencia:"Secretaria da escola: (85) 3421-0090",
          observacoes:"Atividade obrigatória com nota atribuída em Ciências. Alunos que não comparecerem farão atividade avaliativa substitutiva.",
        }},
      {titulo:"Autorização para saída antecipada",status:"recusada",tipo:"saida",desc:"Solicitação pontual de saída antecipada em 12/03/2026 para consulta médica particular.",meta:["📅 Enviada em 10/03/2026","✔️ Respondida em 10/03/2026"],pend:false,
        detalhes:{
          data:"12/03/2026",
          horarioSaida:"10h30 (durante o 3º horário)",
          motivo:"Consulta médica particular",
          retiradoPor:"Carla Andrade Souza (mãe/responsável)",
          motivoRecusa:"Solicitação enviada fora do prazo mínimo de 24h exigido pela secretaria",
        }},
    ],
  },
  {
    name:"Miguel Souza",first:"Miguel",initials:"MS",turma:"3º Ano A",mat:"2026004522",
    turno:"Turno tarde",curso:"Ensino Fundamental I",situacao:"Cursando",
    home:{media:"9,1",freq:"98%",comunicados:1,autorizacoes:1},
    calendarioSubtitle:"Datas, feriados, avaliações e eventos do ano letivo. Itens destacados dizem respeito à turma de Miguel (3º Ano A).",
    horarioNota:"Sala-base: Sala 04, exceto Educação Física (Quadra poliesportiva) e Arte (Sala de Artes).",
    horario:[
      {time:"13:00–13:50",cells:[{s:"Português",p:"Profa. Camila Rocha"},{s:"Matemática",p:"Prof. Eduardo Nogueira"},{s:"Ciências",p:"Profa. Juliana Prado"},{s:"História",p:"Prof. Diego Barros"},{s:"Educação Física",p:"Prof. Rafael Costa",room:"Quadra poliesportiva"}]},
      {time:"13:50–14:40",cells:[{s:"Matemática",p:"Prof. Eduardo Nogueira"},{s:"Português",p:"Profa. Camila Rocha"},{s:"Geografia",p:"Profa. Fernanda Lima"},{s:"Ciências",p:"Profa. Juliana Prado"},{s:"Português",p:"Profa. Camila Rocha"}]},
      {breakRow:"INTERVALO · 14:40 – 15:00"},
      {time:"15:00–15:50",cells:[{s:"Arte",p:"Profa. Beatriz Nunes",room:"Sala de Artes"},{s:"Ciências",p:"Profa. Juliana Prado"},{s:"Matemática",p:"Prof. Eduardo Nogueira"},{s:"Geografia",p:"Profa. Fernanda Lima"},{s:"Ensino Religioso",p:"Profa. Sônia Martins"}]},
      {time:"15:50–16:40",cells:[{s:"História",p:"Prof. Diego Barros"},{s:"Educação Física",p:"Prof. Rafael Costa",room:"Quadra poliesportiva"},{s:"Português",p:"Profa. Camila Rocha"},{s:"Matemática",p:"Prof. Eduardo Nogueira"},{s:"Arte",p:"Profa. Beatriz Nunes",room:"Sala de Artes"}]},
    ],
    boletim:{
      badge:"Aprovado · Média 9,1",
      rows:[
        {d:"Português",n:["9,0","9,2","8,8","9,5"],avg:"9,1"},
        {d:"Matemática",n:["9,5","9,0","9,2","9,3"],avg:"9,3"},
        {d:"Ciências",n:["8,8","9,0","9,0","9,2"],avg:"9,0"},
        {d:"História",n:["9,0","8,7","9,0","9,1"],avg:"9,0"},
        {d:"Geografia",n:["8,7","5,9","9,0","9,0"],avg:"8,2",low:2},
        {d:"Arte",n:["9,8","9,5","9,7","9,9"],avg:"9,7"},
        {d:"Educação Física",n:["9,5","9,8","9,6","9,9"],avg:"9,7"},
      ],
    },
    frequencia:{
      badge:"Frequência regular",
      summary:[
        {v:"420",l:"Total de aulas"},{v:"412",l:"Presenças",cls:"hi"},{v:"8",l:"Faltas",cls:"warn"},
        {v:"98%",l:"Frequência geral",cls:"hi"},{v:"7",l:"Faltas justificadas"},{v:"1",l:"Faltas não justificadas",cls:"warn"},
      ],
      disciplinas:[
        {d:"Português",aulas:90,pres:89,falt:1,freq:"98,9%"},{d:"Matemática",aulas:90,pres:88,falt:2,freq:"97,8%"},
        {d:"Ciências",aulas:60,pres:59,falt:1,freq:"98,3%"},{d:"História",aulas:60,pres:58,falt:2,freq:"96,7%"},
        {d:"Geografia",aulas:60,pres:59,falt:1,freq:"98,3%"},{d:"Arte",aulas:30,pres:29,falt:1,freq:"96,7%"},
        {d:"Educação Física",aulas:30,pres:30,falt:0,freq:"100%"},
      ],
      justificativas:[
        {data:"08/04/2026",d:"Matemática",motivo:"Consulta médica",ok:true},
        {data:"19/05/2026",d:"História",motivo:"Atestado médico",ok:true},
        {data:"30/06/2026",d:"Geografia",motivo:"Viagem em família (com atestado)",ok:true},
      ],
    },
    autorizacoes:[
      {titulo:"Autorização para visita ao Zoológico",status:"pendente",tipo:"excursao",desc:"Visita pedagógica ao Zoológico Municipal. Saída às 13h e retorno às 17h, com acompanhamento de professores.",meta:["📅 Enviada em 10/08/2026","⏳ Prazo de resposta: 17/08/2026"],pend:true,
        detalhes:{
          local:"Zoológico Municipal",
          data:"24/08/2026 (segunda-feira)",
          saida:"13h00 — Portão principal da escola",
          retorno:"17h00 (previsto) — mesmo local de saída",
          transporte:"Ônibus fretado pela escola (ida e volta)",
          responsaveis:"Profa. Juliana Prado e Prof. Diego Barros",
          custo:"R$ 15,00 (entrada) — pagamento via secretaria até 20/08/2026",
          levar:"Uniforme escolar, garrafa de água, boné e lanche",
          contatoEmergencia:"Secretaria da escola: (85) 3421-0090",
          observacoes:"Alunos com alergias ou restrições alimentares devem informar a professora responsável com antecedência.",
        }},
      {titulo:"Autorização para uso de imagem",status:"autorizada",tipo:"imagem",desc:"Uso de fotos e vídeos do aluno em eventos escolares para divulgação em redes sociais oficiais da escola.",meta:["📅 Enviada em 05/02/2026","✔️ Respondida em 06/02/2026"],pend:false,
        detalhes:{
          finalidade:"Divulgação institucional em redes sociais, mural e site da escola",
          validade:"Ano letivo de 2026, podendo ser renovada anualmente",
          canais:"Instagram, Facebook e site oficiais da escola",
          revogacao:"A autorização pode ser revogada a qualquer momento mediante solicitação por escrito à secretaria",
        }},
      {titulo:"Autorização para Festa Junina",status:"autorizada",tipo:"evento",desc:"Participação nas apresentações da Festa Junina da escola, no período da tarde.",meta:["📅 Enviada em 30/05/2026","✔️ Respondida em 02/06/2026"],pend:false,
        detalhes:{
          local:"Quadra poliesportiva da escola",
          data:"20/06/2026 (sábado)",
          horario:"14h00 às 18h00",
          traje:"Traje junino (roupa xadrez), fornecido pela escola no dia do ensaio",
          responsaveis:"Profa. Sônia Martins",
          observacoes:"Pais e responsáveis estão convidados a participar do evento.",
        }},
    ],
  },
];
export const COMUNICADOS = [
  {ic:"📣",titulo:"Reunião de Pais e Responsáveis",isNew:true,meta:"20/08/2026 · Secretaria da Educação",resumo:"Reunião do 2º semestre às 09h30, no auditório da escola, com apresentação do desempenho das turmas."},
  {ic:"📝",titulo:"Informações sobre o calendário de avaliações",isNew:true,meta:"18/08/2026 · Coordenação Pedagógica",resumo:"Divulgado o cronograma de avaliações do 3º bimestre. Confira as datas na tela de Calendário Letivo."},
  {ic:"🕒",titulo:"Alteração no horário das aulas",isNew:true,meta:"14/08/2026 · Secretaria Escolar",resumo:"A partir de 17/08, a aula de Educação Física do 8º Ano A passa a ocorrer às quartas-feiras."},
  {ic:"🎉",titulo:"Comunicado sobre feriado",isNew:false,meta:"05/08/2026 · Secretaria da Educação",resumo:"Não haverá aula no dia 12 de outubro em razão do feriado de Nossa Senhora Aparecida e Dia das Crianças."},
  {ic:"🚌",titulo:"Passeio escolar — Feira de Ciências",isNew:false,meta:"20/05/2026 · Coordenação Pedagógica",resumo:"Enviada autorização para a visita técnica à Feira de Ciências Municipal. Consulte a tela de Autorizações."},
  {ic:"📄",titulo:"Entrega dos boletins",isNew:false,meta:"28/04/2026 · Secretaria Escolar",resumo:"Os boletins do 1º bimestre já estão disponíveis para consulta na tela de Boletim."},
];
export const CALENDARIO_EVENTOS = [
  {d:"02",m:"Fev",titulo:"Início do ano letivo",cat:"letivo",pill:"Dia Letivo"},
  {d:"17",m:"Fev",titulo:"Carnaval",cat:"feriado",pill:"Feriado"},
  {d:"10",m:"Mar",titulo:"Reunião de pais e responsáveis — 1º bimestre",cat:"reuniao",pill:"Reunião",highlight:true},
  {d:"20",m:"Mar",titulo:"Avaliação de Matemática — 8º Ano A",cat:"avaliacao",pill:"Avaliação",highlight:true},
  {d:"10",m:"Abr",titulo:"Feriado municipal",cat:"feriado",pill:"Feriado"},
  {d:"17",m:"Abr",titulo:"Sexta-feira Santa",cat:"feriado",pill:"Feriado"},
  {d:"30",m:"Abr",titulo:"Encerramento do 1º bimestre",cat:"encerramento",pill:"Encerramento",highlight:true},
  {d:"04",m:"Mai",titulo:"Semana de avaliações do 2º bimestre",cat:"avaliacao",pill:"Avaliação"},
  {d:"15",m:"Mai",titulo:"Reunião de responsáveis",cat:"reuniao",pill:"Reunião"},
  {d:"12",m:"Jun",titulo:"Festa Junina da escola",cat:"evento",pill:"Evento escolar"},
  {d:"24",m:"Jun",titulo:"Período de recuperação do 2º bimestre",cat:"avaliacao",pill:"Recuperação"},
  {d:"30",m:"Jun",titulo:"Encerramento do 2º bimestre",cat:"encerramento",pill:"Encerramento"},
  {d:"01",m:"Jul",titulo:"Recesso escolar (férias de julho)",cat:"recesso",pill:"Recesso"},
  {d:"10",m:"Ago",titulo:"Retorno às aulas",cat:"letivo",pill:"Dia Letivo"},
  {d:"20",m:"Ago",titulo:"Reunião de pais — 2º semestre",cat:"reuniao",pill:"Reunião",highlight:true},
  {d:"15",m:"Set",titulo:"Conselho de classe",cat:"evento",pill:"Conselho de Classe"},
  {d:"30",m:"Set",titulo:"Encerramento do 3º bimestre",cat:"encerramento",pill:"Encerramento"},
  {d:"12",m:"Out",titulo:"Feriado — N. Sra. Aparecida / Dia das Crianças",cat:"feriado",pill:"Feriado"},
  {d:"20",m:"Nov",titulo:"Feriado — Consciência Negra",cat:"feriado",pill:"Feriado"},
  {d:"10",m:"Dez",titulo:"Entrega dos boletins finais",cat:"evento",pill:"Evento escolar"},
  {d:"18",m:"Dez",titulo:"Encerramento do ano letivo",cat:"encerramento",pill:"Encerramento"},
];
