spring.application.name=Api

# PostgreSQL - Aiven
spring.datasource.url=jdbc:postgresql://pg-3d09698c-ednafreire544-9f0e.h.aivencloud.com:21141/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações do Supabase Storage
supabase.url=https://prkucaihmjxmccnbybrl.supabase.co
supabase.key=${DB_PASSWORD}
supabase.bucket=atestados

# Limite máximo para arquivos individuais
spring.servlet.multipart.max-file-size=50MB

# Limite máximo total para a requisição inteira
spring.servlet.multipart.max-request-size=50MB

server.port=8081    
